### PR TITLE
Give canvas tag an explicit size.

### LINKED ISSUE #8: Cursor position shifts when resizing
This is pretty easy to reproduce. When I have the cursor near the right side of the window and then resize, I need to be very careful to resize the window such that the cursor remains lined up with the characters in the window, otherwise it moves off the character grid:

Working properly:
screen shot 2015-02-20 at 7 57 25 am

Resized horizontally:
screen shot 2015-02-20 at 7 57 44 am

The same issue happens vertically:
screen shot 2015-02-20 at 7 58 03 am

### PR DESCRIPTION
**Pull request by rygwdn**
Fixes #8
- Set the size in px of the canvas during resize. This avoids having the
  canvas stretch when the size of the window does not exactly line up
  with the expected size.
- When handling a resize, only change the size of the window if the
  window size doesn't match what is expected for the current number
  of rows/columns
- Fill the background of the window with the theme background color

### CODE REVIEW

**Comment by coolwanglu** [comment]
Do you mean that sometimes the size of a window does not respect to the parameters to `window.resize` ?

**Comment by rygwdn** [comment]
It works fine when `window.resizeTo` is called, but when it's not called the canvas gets stretched. It doesn't get called if the window is resized by the mouse but doesn't change the number of rows or columns. This happens pretty consistently for me if I drag the window corner, hold it for a moment, then let go - the window size changes by a few pixels between when I stopped trying to move the cursor and when I let go.

File: src/nvim/ui.coffee [hunk 1]
```diff
@@ -93,14 +93,16 @@ class UI extends EventEmitter
...
+      if not @resize_timer
+        @resize_timer = setTimeout =>
+          @resize_timer = null
+          col = Math.floor window.innerWidth / @char_width
+          row = Math.floor window.innerHeight / @char_height
+
+          if col != @total_col or row != @total_row
+            @emit 'resize', col, row
+
+        , 250
```
Comment (coolwanglu) [inline src/nvim/ui.coffee:105]: why 250?

**Comment by coolwanglu** [comment]
I tried your patch, which works fine. Thanks!

File: src/nvim/ui.coffee (hunk 1 above)
Comment (rygwdn) [inline src/nvim/ui.coffee:105]: mostly arbitrary. I wanted the grid to resize while dragging the window, but don't want to flood neovim. I would welcome a better way to handle it :smile:

Comment (coolwanglu) [inline src/nvim/ui.coffee:105]: I see.
