### PR TITLE
Handle unicode characters.

### LINKED ISSUE #10: Incorrect rendering of airline statusline
I'm using [airline](https://github.com/bling/vim-airline) for my statusbar. It works fine with the new neovim terminal UI, but doesn't work properly in neovim.as:

TUI:
screen shot 2015-02-20 at 8 15 10 am

Neovim.AS:
screen shot 2015-02-20 at 8 15 23 am

### PR DESCRIPTION
**Pull request by rygwdn**
Fixes #10
- Neovim sends the bytes for each individual column separately, so use
  that data to determine the width of the characters.
- Also fix grouping of chars for 'put' to make painting more efficient.

### CODE REVIEW

File: src/nvim/ui.coffee [hunk 1]
```diff
@@ -2,6 +2,7 @@
 # handle redraw events from neovim
 # Copyright (c) 2015 Lu Wang <coolwanglu@gmail.com>
 
+punycode = require 'punycode'
```
Comment (coolwanglu) [inline src/nvim/ui.coffee]: If a new module is introduced, please add it to `package.json`

Comment (rygwdn) [inline src/nvim/ui.coffee]: I wasn't sure if this was necessary since `punycode` is included in `node.js` (and thus atom-shell) by default. I can add it though

Comment (coolwanglu) [inline src/nvim/ui.coffee]: Ah I see. Thanks for the clarification.

Comment (coolwanglu) [inline src/nvim/ui.coffee]: No need to add it then.

**Comment by coolwanglu** [comment]
How about the `maxWidth` parameter for `fillText`, I think it should also be change this way.

**Comment by rygwdn** [comment]
@coolwanglu @kopischke I just pushed a new version that lets neovim determine how many columns there are. It should also speed up painting of characters

**Comment by coolwanglu** [comment]
@rygwdn This looks interesting, why the old version was not working? Maybe some Unicode characters are mis-interpreted by the browser? How about special Unicode characters and double-width characters?

**Comment by rygwdn** [comment]
The main issue was in `handle_redraw`, which was never actually handling `put` specially. It looks like the values inside the event are not actually strings, so `e[0] == 'put'` is never true. The next issue was in joining all the characters, since that would require re-calculating the number of columns (since `"some string".length` in JS is the number of bytes, not the number of columns). Then I needed to add in the loop to draw the characters individually because the spacing used for the grid apparently doesn't exactly line up with how the canvas draws it.

I determined that `put` provides the columns individually by looking at some of the other neovim UI implementations (specifically the [python GTK](https://github.com/neovim/python-client/blob/c1f2bc580a9f777b8cac26f9e564853853e6bf3a/neovim/ui/screen.py#L91) one and the [C++ Qt](https://github.com/equalsraf/neovim-qt/blob/60d6e302da153fd913a59c183913c76bebe57374/src/gui/shell.cpp#L202) one) where they just handle each `put` individually and increase the column by `1`. I'm not sure how it will handle weird cases, but at the moment this should handle them the same way

**Comment by coolwanglu** [comment]
OK I see. Thanks!
